---
# defaults/main.yml for dsm_replication_setup

# Target host
dsm_replication_setup_host: ""

# Authentication
dsm_replication_setup_username: ""
dsm_replication_setup_password: ""
dsm_replication_setup_api_key: ""

# Behavior
dsm_replication_setup_validate_certs: true
dsm_replication_setup_state: present
